config/routes.rb
Rails.application.routes.draw do
  root 'cars#index'

  resources :cars
  resources :manifacturers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :manifacturer

  enum :power_type, %i[disel petrol eletric hybrid]
  enum emission_standard: %w[euro6 lev ulev zev].index_by(&:itself)
end

app/models/manifacturer.rb
class Manifacturer < ApplicationRecord
  def to_combobox_display
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show; end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit; end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy!

    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def car_params
    params.require(:car).permit(:name, :manifacturer_id, :power_type, :emission_standard)
  end
end

app/controllers/manifacturers_controller.rb
class ManifacturersController < ApplicationController
  before_action :set_manifacturer, only: %i[show edit update destroy]

  # GET /manifacturers or /manifacturers.json
  def index
    set_page_and_extract_portion_from Manifacturer.all

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  # GET /manifacturers/1 or /manifacturers/1.json
  def show; end

  # GET /manifacturers/new
  def new
    @manifacturer = Manifacturer.new
  end

  # GET /manifacturers/1/edit
  def edit; end

  # POST /manifacturers or /manifacturers.json
  def create
    @manifacturer = Manifacturer.new(manifacturer_params)

    respond_to do |format|
      if @manifacturer.save
        format.html { redirect_to manifacturer_url(@manifacturer), notice: 'Manifacturer was successfully created.' }
        format.json { render :show, status: :created, location: @manifacturer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @manifacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manifacturers/1 or /manifacturers/1.json
  def update
    respond_to do |format|
      if @manifacturer.update(manifacturer_params)
        format.html { redirect_to manifacturer_url(@manifacturer), notice: 'Manifacturer was successfully updated.' }
        format.json { render :show, status: :ok, location: @manifacturer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @manifacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manifacturers/1 or /manifacturers/1.json
  def destroy
    @manifacturer.destroy!

    respond_to do |format|
      format.html { redirect_to manifacturers_url, notice: 'Manifacturer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_manifacturer
    @manifacturer = Manifacturer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def manifacturer_params
    params.require(:manifacturer).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/manifacturers_helper.rb
module ManifacturersHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Name:</strong>
    <%= car.name %>
  </p>

  <p>
    <strong>Manifacturer:</strong>
    <%= car.manifacturer_id %>
  </p>

</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  
  <div>
    <%= form.label :manifacturer_id, style: "display: block" %>
    <%= form.combobox :manifacturer_id, manifacturers_path %>
  </div>

  <div>
    <%= form.label :power_type, style: "display: block" %>
    <%#= form.combobox :power_type, Car.power_types %>
    <%= form.select :power_type, options_for_select(Car.power_types.map {|key, value| [key, Car.power_types.key(value)] }) %>
  </div>

  <div>
    <%= form.label :emission_standard, style: "display: block" %>
    <%= form.combobox :emission_standard, Car.emission_standards %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car %> |
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cars</h1>

<div id="cars">
  <% @cars.each do |car| %>
    <%= render car %>
    <p>
      <%= link_to "Show this car", car %>
    </p>
  <% end %>
</div>

<%= link_to "New car", new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @car %>

<div>
  <%= link_to "Edit this car", edit_car_path(@car) %> |
  <%= link_to "Back to cars", cars_path %>

  <%= button_to "Destroy this car", @car, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cmbx</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= combobox_style_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/manifacturers/_form.html.erb
<%= form_with(model: manifacturer) do |form| %>
  <% if manifacturer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(manifacturer.errors.count, "error") %> prohibited this manifacturer from being saved:</h2>

      <ul>
        <% manifacturer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/manifacturers/_manifacturer.html.erb
<div id="<%= dom_id manifacturer %>">
  <p>
    <strong>Name:</strong>
    <%= manifacturer.name %>
  </p>

</div>

app/views/manifacturers/edit.html.erb
<h1>Editing manifacturer</h1>

<%= render "form", manifacturer: @manifacturer %>

<br>

<div>
  <%= link_to "Show this manifacturer", @manifacturer %> |
  <%= link_to "Back to manifacturers", manifacturers_path %>
</div>

app/views/manifacturers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Manifacturers</h1>

<div id="manifacturers">
  <% @manifacturers.each do |manifacturer| %>
    <%= render manifacturer %>
    <p>
      <%= link_to "Show this manifacturer", manifacturer %>
    </p>
  <% end %>
</div>

<%= link_to "New manifacturer", new_manifacturer_path %>

app/views/manifacturers/index.turbo_stream.erb
<%= async_combobox_options @page.records, next_page: @page.last? ? nil : @page.next_param %>

app/views/manifacturers/new.html.erb
<h1>New manifacturer</h1>

<%= render "form", manifacturer: @manifacturer %>

<br>

<div>
  <%= link_to "Back to manifacturers", manifacturers_path %>
</div>

app/views/manifacturers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @manifacturer %>

<div>
  <%= link_to "Edit this manifacturer", edit_manifacturer_path(@manifacturer) %> |
  <%= link_to "Back to manifacturers", manifacturers_path %>

  <%= button_to "Destroy this manifacturer", @manifacturer, method: :delete %>
</div>